-- =====================================================
-- BRIXAUREA AI BRAIN: SCENARIO STICKY INTELLIGENCE
-- =====================================================
-- Adds persistent AI analysis fields to the scenarios table.
-- =====================================================

ALTER TABLE public.financial_scenarios 
ADD COLUMN IF NOT EXISTS health_score INTEGER CHECK (health_score >= 0 AND health_score <= 100),
ADD COLUMN IF NOT EXISTS strategic_analysis TEXT;

COMMENT ON COLUMN public.financial_scenarios.health_score IS 'Proprietary AI Health Score (0-100)';
COMMENT ON COLUMN public.financial_scenarios.strategic_analysis IS 'Detailed strategic verdict generated by the BrixAurea AI Brain.';
