ALTER TABLE units_mix
ADD COLUMN IF NOT EXISTS bedrooms NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bathrooms NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS suites INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS garages INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS area_total NUMERIC DEFAULT 0;
