-- MIGRATION: Add technical columns to floor_plan_library
-- Run this in Supabase SQL Editor

ALTER TABLE floor_plan_library 
ADD COLUMN IF NOT EXISTS half_baths INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS stories INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS plan_width_lf DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS plan_depth_lf DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_pool BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS living_area_sqft DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS entry_area_sqft DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lanai_area_sqft DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS garage_area_sqft DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_const_area_sqft DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS file_url TEXT;
