'use client';

import { useState, useEffect } from 'react';
import { createClient } from '@/lib/supabase/client';
import ConfirmModal from '@/components/ui/ConfirmModal';

export default function MFASettings({ lang }: { lang: string }) {
    const [enabled, setEnabled] = useState(false);
    const [loading, setLoading] = useState(true);
    const [enrollmentData, setEnrollmentData] = useState<{ id: string; qr_code: string; secret: string } | null>(null);
    const [verifyCode, setVerifyCode] = useState('');
    const [error, setError] = useState('');
    const [setupStep, setSetupStep] = useState<'idle' | 'qr' | 'success'>('idle');
    const [confirmModalOpen, setConfirmModalOpen] = useState(false);

    const supabase = createClient();

    const t = {
        pt: {
            title: 'Autenticação de Dois Fatores (2FA)',
            desc: 'Adicione uma camada extra de segurança à sua conta.',
            status_on: 'Ativado',
            status_off: 'Desativado',
            enable: 'Configurar 2FA',
            disable: 'Desativar 2FA',
            scan_qr: '1. Scaneie este QR Code com seu App Autenticador (Google Auth, Authy, etc).',
            enter_code: '2. Digite o código de 6 dígitos gerado pelo App:',
            verify: 'Verificar e Ativar',
            cancel: 'Cancelar',
            secret: 'Segredo (se não conseguir scanear):',
            success: '2FA Ativado com sucesso!',
            error_verify: 'Código inválido. Tente novamente.',
            modal_title: 'Desativar 2FA',
            modal_message: 'Tem certeza que deseja desativar a autenticação de dois fatores? Isso reduzirá a segurança da sua conta.',
            modal_confirm: 'Desativar',
            modal_cancel: 'Cancelar',
        },
        en: {
            title: 'Two-Factor Authentication (2FA)',
            desc: 'Add an extra layer of security to your account.',
            status_on: 'Enabled',
            status_off: 'Disabled',
            enable: 'Setup 2FA',
            disable: 'Disable 2FA',
            scan_qr: '1. Scan this QR Code with your Authenticator App (Google Auth, Authy, etc).',
            enter_code: '2. Enter the 6-digit code generated by the App:',
            verify: 'Verify & Activate',
            cancel: 'Cancel',
            secret: 'Secret (if you cannot scan):',
            success: '2FA Enabled successfully!',
            error_verify: 'Invalid code. Please try again.',
            modal_title: 'Disable 2FA',
            modal_message: 'Are you sure you want to disable Two-Factor Authentication? This will reduce your account security.',
            modal_confirm: 'Disable',
            modal_cancel: 'Cancel',
        }
    };

    const text = lang === 'pt' ? t.pt : t.en;

    useEffect(() => {
        checkMFA();
    }, []);

    const checkMFA = async () => {
        const { data, error } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
        if (!error && data) {
            const { data: factors } = await supabase.auth.mfa.listFactors();
            const verified = factors?.all?.filter(f => f.status === 'verified') || [];
            setEnabled(verified.length > 0);
        }
        setLoading(false);
    };

    const startEnrollment = async () => {
        console.log('Starting enrollment...');
        setLoading(true);
        setError('');

        try {
            // Cleanup: Remove any stale unverified factors
            const { data: factors } = await supabase.auth.mfa.listFactors();
            if (factors?.all) {
                const unverified = factors.all.filter(f => f.status === 'unverified' && f.factor_type === 'totp');
                for (const factor of unverified) {
                    console.log('Removing stale factor:', factor.id);
                    await supabase.auth.mfa.unenroll({ factorId: factor.id });
                }
            }

            const { data, error } = await supabase.auth.mfa.enroll({
                factorType: 'totp',
            });

            if (error) {
                console.error('MFA Enroll Error:', error);
                setError(error.message);
                alert(`Error: ${error.message}`); // Immediate feedback
                setLoading(false);
                return;
            }

            console.log('Enrollment data received:', data);
            setEnrollmentData({
                id: data.id,
                qr_code: data.totp.qr_code,
                secret: data.totp.secret,
            });
            setSetupStep('qr');
        } catch (err) {
            console.error('Unexpected error:', err);
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            alert(`Unexpected error: ${(err as any).message || err}`);
        } finally {
            setLoading(false);
        }
    };

    const handleVerify = async () => {
        if (!enrollmentData) return;
        setError('');

        const { data, error } = await supabase.auth.mfa.challenge({
            factorId: enrollmentData.id,
        });

        if (error) {
            setError(error.message);
            return;
        }

        const { data: verifyData, error: verifyError } = await supabase.auth.mfa.verify({
            factorId: enrollmentData.id,
            challengeId: data.id,
            code: verifyCode,
        });

        if (verifyError) {
            setError(text.error_verify);
        } else {
            setSetupStep('success');
            setEnabled(true);
            setTimeout(() => {
                setSetupStep('idle');
                setEnrollmentData(null);
                setVerifyCode('');
            }, 3000);
        }
    };

    const handleDisableClick = () => {
        setConfirmModalOpen(true);
    };

    const confirmDisable = async () => {
        const { data: factors } = await supabase.auth.mfa.listFactors();
        const totpFactor = factors?.all?.find(f => f.factor_type === 'totp' && f.status === 'verified');

        if (totpFactor) {
            await supabase.auth.mfa.unenroll({ factorId: totpFactor.id });
            setEnabled(false);
        }
        setConfirmModalOpen(false);
    };

    return (
        <div className="space-y-4">
            <div className="flex items-center justify-between">
                <div>
                    <h3 className="text-lg font-medium text-gray-900">{text.title}</h3>
                    <p className="text-sm text-gray-500">{text.desc}</p>
                    <div className="mt-2">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${enabled ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                            }`}>
                            {enabled ? text.status_on : text.status_off}
                        </span>
                    </div>
                </div>
                {!enabled && setupStep === 'idle' && (
                    <button
                        onClick={startEnrollment}
                        disabled={loading}
                        className="px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-cyan-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500"
                    >
                        {text.enable}
                    </button>
                )}
                {enabled && (
                    <button
                        onClick={handleDisableClick}
                        className="px-4 py-2 border border-gray-300 text-sm font-medium rounded-md shadow-sm text-gray-700 bg-white hover:bg-gray-50 focus:outline-none"
                    >
                        {text.disable}
                    </button>
                )}
            </div>

            {/* Enrollment UI */}
            {setupStep === 'qr' && enrollmentData && (
                <div className="bg-gray-50 p-6 rounded-xl border border-gray-200 mt-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                        <div className="flex flex-col items-center">
                            <div className="bg-white p-4 rounded-lg shadow-sm">
                                {/* Supabase returns a Data URI (SVG) for qr_code, so we render it as an image */}
                                <img src={enrollmentData.qr_code} alt="QR Code" width={180} height={180} />
                            </div>
                            <p className="text-xs text-gray-400 mt-2 font-mono break-all text-center max-w-[200px]">
                                {text.secret} {enrollmentData.secret}
                            </p>
                        </div>
                        <div className="space-y-4">
                            <div>
                                <p className="font-medium text-gray-900 mb-1">{text.scan_qr}</p>
                            </div>

                            <div>
                                <p className="font-medium text-gray-900 mb-2">{text.enter_code}</p>
                                <div className="flex gap-2">
                                    <input
                                        type="text"
                                        value={verifyCode}
                                        onChange={(e) => setVerifyCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                                        placeholder="000 000"
                                        className="block w-full text-center tracking-[0.5em] text-xl font-bold rounded-md border-gray-300 shadow-sm focus:border-cyan-500 focus:ring-cyan-500 py-3"
                                    />
                                </div>
                                {error && (
                                    <p className="text-red-600 text-sm mt-2">{error}</p>
                                )}
                            </div>

                            <div className="flex gap-3 pt-2">
                                <button
                                    onClick={() => { setSetupStep('idle'); setEnrollmentData(null); }}
                                    className="px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                                >
                                    {text.cancel}
                                </button>
                                <button
                                    onClick={handleVerify}
                                    disabled={verifyCode.length !== 6}
                                    className="flex-1 px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-cyan-700 disabled:opacity-50"
                                >
                                    {text.verify}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {setupStep === 'success' && (
                <div className="bg-green-50 p-4 rounded-xl border border-green-200 mt-4 flex items-center gap-3 text-green-700">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    {text.success}
                </div>
            )}

            <ConfirmModal
                isOpen={confirmModalOpen}
                onClose={() => setConfirmModalOpen(false)}
                onConfirm={confirmDisable}
                title={text.modal_title}
                message={text.modal_message}
                confirmText={text.modal_confirm}
                cancelText={text.modal_cancel}
                isDestructive={true}
            />
        </div>
    );
}
